# Generated by Django 2.0.5 on 2018-08-15 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180815_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolCamb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('solicitudot', models.TextField()),
                ('order_id', models.TextField()),
                ('cliente', models.TextField()),
                ('fechabpt', models.TextField()),
                ('maquina', models.TextField()),
                ('approved_cambio', models.BooleanField(default=False)),
            ],
        ),
    ]
