# Generated by Django 2.0.5 on 2018-08-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_solcamb'),
    ]

    operations = [
        migrations.AddField(
            model_name='solcamb',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solcamb',
            name='title',
            field=models.CharField(default='hola', max_length=200),
        ),
        migrations.AlterField(
            model_name='solcamb',
            name='cliente',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solcamb',
            name='fechabpt',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solcamb',
            name='maquina',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solcamb',
            name='order_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solcamb',
            name='solicitudot',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solcamb',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
