# Generated by Django 2.0.5 on 2018-08-19 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_appointment_cargacsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCImportacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc', models.CharField(max_length=200)),
                ('proveedor', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mes_arribo_esperado', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
