# Generated by Django 2.0.5 on 2018-08-19 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_ocimportacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='author',
        ),
        migrations.AlterField(
            model_name='ocimportacion',
            name='mes_arribo_esperado',
            field=models.CharField(choices=[('Enero', 'January'), ('Febrero', 'February'), ('Marzo', 'March'), ('Abril', 'April')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ocimportacion',
            name='proveedor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solcamb',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solcamb',
            name='title',
            field=models.CharField(default='holi', max_length=200),
        ),
    ]
