# Generated by Django 2.0.5 on 2018-08-19 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180819_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactindex', models.CharField(max_length=200)),
                ('plantid', models.CharField(blank=True, max_length=200, null=True)),
                ('workcenter', models.CharField(blank=True, max_length=200, null=True)),
                ('orderid', models.CharField(blank=True, max_length=200, null=True)),
                ('setupstartdate', models.CharField(blank=True, max_length=200, null=True)),
                ('setupenddate', models.CharField(blank=True, max_length=200, null=True)),
                ('runstartdate', models.CharField(blank=True, max_length=200, null=True)),
                ('runenddate', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('Patient', models.CharField(blank=True, max_length=200, null=True)),
                ('Date', models.CharField(blank=True, max_length=200, null=True)),
                ('Time', models.CharField(blank=True, max_length=200, null=True)),
                ('Duration', models.CharField(blank=True, max_length=200, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('Clinician', models.CharField(blank=True, max_length=200, null=True)),
                ('AppointmentType', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
