# Generated by Django 2.0.5 on 2018-08-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_prodid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodid',
            name='Duration',
        ),
    ]
