# Generated by Django 2.0.5 on 2018-08-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_prodid_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodid',
            old_name='duration',
            new_name='duracion',
        ),
    ]
