# Generated by Django 2.0.5 on 2018-08-19 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180819_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdID',
        ),
    ]
