# Generated by Django 2.0.5 on 2018-09-12 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenConv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('maquina', models.CharField(max_length=200)),
                ('fechainiprog', models.CharField(max_length=200)),
                ('fechafinprog', models.CharField(max_length=200)),
                ('unisprog', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaConv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato1', models.CharField(default='vacio', max_length=200)),
                ('dato2', models.CharField(default='vacio', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ordenconv',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenconvs', to='blog.ProgramaConv'),
        ),
    ]
