# Generated by Django 2.0.5 on 2018-09-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20180911_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebamod',
            name='ultrafile',
            field=models.TextField(default='hola,que,tal'),
        ),
    ]
