# Generated by Django 2.0.5 on 2018-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_pruebatabla'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norden', models.CharField(default='vacio', max_length=200)),
                ('fechaini', models.CharField(default='vacio', max_length=200)),
                ('fechater', models.CharField(default='vacio', max_length=200)),
                ('duracion', models.CharField(default='vacio', max_length=200)),
            ],
        ),
    ]
