# Generated by Django 2.0.5 on 2018-09-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_ordenprog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenprog',
            old_name='duracion',
            new_name='fecha_programa',
        ),
        migrations.RenameField(
            model_name='ordenprog',
            old_name='fechaini',
            new_name='transaction_index',
        ),
        migrations.RemoveField(
            model_name='ordenprog',
            name='fechater',
        ),
        migrations.RemoveField(
            model_name='ordenprog',
            name='norden',
        ),
    ]
