# Generated by Django 2.0.5 on 2018-09-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20180917_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workcenter', models.CharField(default='vacio', max_length=200)),
                ('orderId', models.CharField(default='vacio', max_length=200)),
                ('dateini', models.CharField(default='vacio', max_length=200)),
                ('datefin', models.CharField(default='vacio', max_length=200)),
                ('qIn', models.CharField(default='vacio', max_length=200)),
                ('orderIdPrev', models.CharField(default='vacio', max_length=200)),
                ('orderIdPost', models.CharField(default='vacio', max_length=200)),
            ],
        ),
    ]
