# Generated by Django 2.0.5 on 2018-09-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_detalleprog'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprog',
            name='programa',
            field=models.ForeignKey(default='vacío', on_delete=django.db.models.deletion.CASCADE, related_name='fecha_prog', to='blog.OrdenProg'),
        ),
    ]
