# Generated by Django 2.0.5 on 2018-09-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_detalleprog_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprog',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_prog', to='blog.OrdenProg'),
        ),
    ]
