# Generated by Django 2.0.5 on 2018-09-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20180917_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='vacio', max_length=200)),
                ('orderId', models.CharField(default='vacio', max_length=200)),
                ('padron', models.CharField(default='vacio', max_length=200)),
                ('datefin', models.CharField(default='vacio', max_length=200)),
                ('qOrd', models.CharField(default='vacio', max_length=200)),
                ('lamDisp', models.CharField(default='vacio', max_length=200)),
                ('nSalidas', models.CharField(default='vacio', max_length=200)),
                ('qProd', models.CharField(default='vacio', max_length=200)),
                ('porcTerm', models.CharField(default='vacio', max_length=200)),
                ('maquina', models.CharField(default='vacio', max_length=200)),
                ('orderIdPrev', models.CharField(default='vacio', max_length=200)),
                ('orderIdPost', models.CharField(default='vacio', max_length=200)),
            ],
        ),
    ]
