# Generated by Django 2.0.5 on 2018-09-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_prodreal'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprog',
            name='datefinajustada',
            field=models.CharField(default='vacio', max_length=200),
        ),
        migrations.AddField(
            model_name='detalleprog',
            name='turno',
            field=models.CharField(default='vacio', max_length=200),
        ),
        migrations.AddField(
            model_name='prodreal',
            name='datefinajustada',
            field=models.CharField(default='vacio', max_length=200),
        ),
        migrations.AddField(
            model_name='prodreal',
            name='turno',
            field=models.CharField(default='vacio', max_length=200),
        ),
    ]
