# Generated by Django 2.0.5 on 2018-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20180930_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenprog',
            name='horizontefin',
            field=models.CharField(default='vacio', max_length=200),
        ),
        migrations.AddField(
            model_name='ordenprog',
            name='horizonteini',
            field=models.CharField(default='vacio', max_length=200),
        ),
    ]
