# Generated by Django 2.0.5 on 2018-10-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20181003_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprog',
            name='completo_fechaturno',
            field=models.CharField(default='vacio', max_length=200),
        ),
        migrations.AddField(
            model_name='detalleprog',
            name='completo_secuencia',
            field=models.CharField(default='vacio', max_length=200),
        ),
        migrations.AddField(
            model_name='detalleprog',
            name='completo_unidades',
            field=models.CharField(default='vacio', max_length=200),
        ),
    ]
