# Generated by Django 2.0.5 on 2018-10-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_maquinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(default='vacio', max_length=10)),
                ('horaini', models.CharField(default='vacio', max_length=100)),
                ('horafin', models.CharField(default='vacio', max_length=100)),
            ],
        ),
    ]
